name: merge-queue
run-name: ${{ github.actor }} is running a merge queue
on: 
  merge_group:
    types: [checks_requested]
    branches:
      - master
    paths:
      - .github/workflows/merge-queue.yml
      - .github/workflows/merge-queue-*.yml
      - .github/merge-queue.yml
      - .github/merge-queue-*.yml
      - .github/merge-group.yml
      - .github/merge-group-*.yml

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

